#ifndef AYED_TPG_1C2024_CONSTANTES_HPP
#define AYED_TPG_1C2024_CONSTANTES_HPP

/*CLASE JUEGO*/
enum OPCIONES_MENU_PRINCIPAL{
    INICIO = 0,
    JUGAR = 1,
    CREDITOS = 2,
    SALIR_MENU_PRINCIPAL = 3,
};

enum CARACTERISTICAS_JUEGO {
    CLIENTES_MAXIMOS = 4,
    LOCALES_MAXIMOS = 4,
    CERO = 0,
    UN_INDICE = 1,
    FILAS = 18,
    COLUMNAS = 24,
};

enum COSTOS_MONEDAS {
    MONEDAS_MINIMAS_INICIO = 15,
    MONEDAS_MAXIMAS_INICIO = 45,
    MONEDAS_POR_CAMINO = 10,
    MONEDAS_PARA_ENTREGAR_RAPIDO = 5,
    MONEDAS_MINIMAS_POR_PEDIDO_ENTREGADO = 0,
    MONEDAS_MAXIMAS_POR_PEDIDO_ENTREGADO = 20,
};

enum OPCIONES_MENU_JUEGO {
    CONTINUAR = 0,
    GENERAR_NUEVO_PEDIDO_ALEATORIO = 1,
    ENTREGAR_PEDIDO = 2,
    MOSTRAR_SENDEROS_CONEXIONES = 3,
    SALIR = 4,
};

enum ESTADO_DEL_JUEGO {
    EN_CURSO = 1,
    FINALIZADO = -1
};

enum class DIRECCION {
    ARRIBA,
    ABAJO,
    IZQUIERDA,
    DERECHA
};


/*CLASE MAPA*/
enum REPRESENTACIONES_MAPA{
    NO_CAMINABLE = 0,
    CAMINABLE = 1,
    JUGADOR = 2,
    LOCAL = 3,
    CAMINO = 4,
};


/*CLASE LOCAL*/
enum NOMBRE_LOCALES {
    LOCAL_ACE,
    BAR_LOCAL,
    LOCAL_CAF,
    DEL_LOCAL,
    LOCAL_ECO,
    FIT_LOCAL,
    LOCAL_GAL,
    HEX_LOCAL,
    LOCAL_ICE,
    JOY_LOCAL,
    LOCAL_KID,
    LOT_LOCAL,
    LOCAL_MIX,
    NUT_LOCAL,
    LOCAL_OAS
};

enum INDICES_LOCALES {
    CANTIDAD_NOMBRES = 15,
};


/*CLASE PEEDIDOS*/
enum PESOS_PAQUETES{
    PESO_MINIMO = 1,
    PESO_MAXIMO = 15,
};

#define PATH_ARCHIVO_CALLEJON "callejon.csv"


#endif